from django.urls import path
from .views import (
    ArticleListView,
    ArticleDetailView,
    VideoListView,
    InvesteeInfoUpdateView,
    InvestorInfoUpdateView,
    UserEmailPasswordUpdateView,
    UserLoginView,
    UserCreateView,
    UserDetailView,
    LogoutView,
    InvestorDataView,
    InvesteeDataView,
    CurrentUserVerificationStatusView,
    EmailReceivedCreateView,
    CertifiedUserDataView,
    OrderTrackingCreateView,
    OrderRetrieveView,
    PaymentVerificationView,
    PasswordResetView,
)


urlpatterns = [
    path('articles/', ArticleListView.as_view(), name='article-list'),
    path('articles/<int:pk>/', ArticleDetailView.as_view(), name='article-detail'),
    path('videos/', VideoListView.as_view(), name='video-list'),
    path('login/', UserLoginView.as_view(), name='user-login'),
    path('password-reset/', PasswordResetView.as_view(), name='password-reset'),
    path('signup/', UserCreateView.as_view(), name='user-create'),
    path('users/<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    path('logout/', LogoutView.as_view(), name='user-logout'),
    path('investors_data/', InvestorDataView.as_view(), name='investor-data'),
    path('investee_data/', InvesteeDataView.as_view(), name='investee-data'),
    path('certified-users/', CertifiedUserDataView.as_view(), name='certified_users_list'),
    path('investor-info/update/<int:pk>/', InvestorInfoUpdateView.as_view(), name='investor_update'),
    path('investee-info/update/<int:pk>/', InvesteeInfoUpdateView.as_view(), name='investor_update'),
    path('email-pass/update/<int:pk>/', UserEmailPasswordUpdateView.as_view(), name='investor_update'),
    path('user/verification-status/', CurrentUserVerificationStatusView.as_view(), name='current-user-verification-status'),
    path('order/track/', OrderTrackingCreateView.as_view(), name='order-track'),
    path('order/retrieve/<str:order_tracking_id>/', OrderRetrieveView.as_view(), name='order-retrieve'),
    path('user/<int:pk>/payment-verification/', PaymentVerificationView.as_view(), name='payment-verification'),

]
