# Generated by Django 4.2.14 on 2024-07-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailreceived',
            name='user',
        ),
        migrations.AddField(
            model_name='emailreceived',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
