# Generated by Django 5.0.6 on 2024-06-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_customuser_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="area_of_interest",
            field=models.CharField(
                blank=True,
                choices=[
                    ("E-commerce Platforms", "E-commerce Platforms"),
                    ("Fintech", "Fintech"),
                    ("HealthTech", "HealthTech"),
                    ("EdTech", "EdTech"),
                    ("SaaS", "SaaS"),
                    ("AI/ML", "AI/ML"),
                    ("Blockchain", "Blockchain"),
                    ("Cybersecurity", "Cybersecurity"),
                    ("Renewable Energy", "Renewable Energy"),
                    ("Biotech", "Biotech"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="membership_tier",
            field=models.CharField(
                blank=True,
                choices=[("Basic", "Basic"), ("Premium", "Premium")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="verification_badge",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Basic", "Basic"),
                    ("Level 1", "Level 1"),
                    ("Level 2", "Level 2"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="verification_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Basic", "Basic"),
                    ("Level 1", "Level 1"),
                    ("Level 2", "Level 2"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
