# Generated by Django 5.0.6 on 2024-06-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_customuser_area_of_interest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_pic_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
