# Generated by Django 5.0.6 on 2024-06-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_customuser_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_phone_verified",
            field=models.BooleanField(default=False),
        ),
    ]
