# Generated by Django 5.0.6 on 2024-06-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_customuser_area_of_interest_article_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="previewText",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
