# Generated by Django 5.0.6 on 2024-07-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_article_previewtext"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleimage",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="area_of_interest",
            field=models.TextField(blank=True, null=True),
        ),
    ]
