# Generated by Django 5.0.6 on 2024-07-04 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_alter_articleimage_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="gallery_images",
            field=models.JSONField(default=list),
        ),
    ]
