# Generated by Django 5.0.6 on 2024-07-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_customuser_gallery_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="membership_tier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Free", "Free"),
                    ("Basic", "Basic"),
                    ("Standard", "Standard"),
                    ("Premium", "Premium"),
                    ("Premium Plus", "Premium Plus"),
                ],
                default="Free",
                max_length=255,
                null=True,
            ),
        ),
    ]
