# Generated by Django 5.0.6 on 2024-07-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_alter_customuser_membership_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="merchant_reference",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="order_tracking_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
