# Generated by Django 5.0.6 on 2024-07-08 00:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_customuser_merchant_reference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="payment_status",
            field=models.CharField(
                blank=True,
                choices=[("Pending", "Pending"), ("Success", "Success")],
                max_length=255,
                null=True,
            ),
        ),
    ]
